apiVersion: v1
kind: Secret
metadata:
  name: {{ template "check-smtp.name" . }}
  labels:
    chart: {{ template "check-smtp.chart" . }}
type: Opaque
data:
  SHARED_KEY:  {{ .Values.application.sharedKey | b64enc | quote }}